### ISSUE TITLE
Issues with TLSv1.3 and the STC website

### ISSUE THREAD

**Issue by manolo20** [StatCan/shiny#14] opened 2020-07-07 19:39 UTC
I think there was an update over the weekend in the STC website that allows only TLSv1.2 and not TLSv1.3.

This is an issue in some of the latest linux OSs (Debian, Ubuntu 20.04 LTS) when downloading a CODR table from R with the```library(cansim)``` (or ```file.download()```). The ```cansim``` R library is used in the [EV](https://github.com/StatCan/R-dashboards/pull/21) shiny application. 

Some potential solutions are to modify the openssl.cnf or to allow both versions of TLS.

@ca-scribner @blairdrummond

**Comment by ca-scribner** [comment] 2020-07-07 19:43
I think we'd need @zachomedia to weigh in on this.  

The issue is the same as [here](https://github.com/mountainMath/cansim/issues/77)

**Comment by blairdrummond** [comment] 2020-07-07 19:47
Thanks for finding that issue @ca-scribner ; yeah tbh that looks like the kind of thing that STC needs to fix on its end. But will let @zachomedia weigh in

**Comment by manolo20** [comment] 2020-07-07 20:00
What is puzzling is that @ca-scribner got the application to work on July 3rd on a Debian OS without changing the openssl.cnf.

**Comment by ca-scribner** [comment] 2020-07-07 20:08
Does the shiny app always download data, or only if it’s stale? I remember
you me ruining something about that. Was it pushed on Friday with fresh
data, so I didn’t hit the issue till Monday?

**Comment by manolo20** [comment] 2020-07-07 20:13
You are right, the application would not have downloaded any information on Friday.

**Comment by zachomedia** [comment] 2020-07-08 15:11
This is an issue with the StatCan website(s) and will need to be fixed there. I've already been in contact with the team responsible for the website and made them aware of this.

**Comment by ca-scribner** [comment] 2020-07-08 15:22
In the interim we'll apply the patch on our side to avoid the issue.  Maybe not today, but hopefully today/tomorrow?  Once that's done, I'll also merge Statcan/R-dashboards#21

**Comment by ca-scribner** [comment] 2020-07-13 17:52
The temporary fix to the shiny server seems to be working.  The [ev dashboard](https://shiny.covid.cloud.statcan.ca/ev-data-viz/) would have needed to download new data by now.

**Comment by ca-scribner** [comment] 2020-07-13 18:00
Closing the issue as "solved" but I'll make a backloged issue to actually fix this for real when STC gets things sorted

**Closed as completed by ca-scribner** 2020-07-13 18:00 UTC
Labels: size/S, component/r-shiny
